name: Deploy Project

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Build project
              run: npm run build-project

            - name: Deploy project
              run: npm run deploy-project -- --ci 
              env:
                  GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
